Repository loro-dev/loro, pull requests merged in 2024-01, with the labels that each got.

#233 Make InternalString a newtype
  Cargo.lock
  crates/loro-common/Cargo.toml
  crates/loro-common/src/internal_string.rs
  crates/loro-common/src/lib.rs
  crates/loro-internal/Cargo.toml
  crates/loro-internal/src/encoding/encode_reordered.rs
  crates/loro-internal/src/lib.rs
  crates/loro-internal/src/loro.rs
  crates/loro-internal/src/state/map_state.rs
Labels: refactor

#232 Fix tracker delete error when the update is partially included
  crates/loro-internal/src/container/richtext/tracker.rs
  crates/loro-internal/src/fuzz/richtext.rs
  crates/loro-internal/tests/test.rs
Labels: bug

#231 Update loro_value! macro and add binary support
  crates/loro-common/src/macros.rs
  crates/loro-common/src/value.rs
  crates/loro-internal/src/encoding/encode_reordered.rs
  crates/loro-internal/src/state/tree_state.rs
Labels: documentation

#245 refactor: setting parent only in state
  crates/loro-internal/fuzz/Cargo.lock
  crates/loro-internal/src/diff_calc.rs
  crates/loro-internal/src/fuzz/tree.rs
  crates/loro-internal/src/handler.rs
  crates/loro-internal/src/state.rs
  crates/loro-internal/src/state/list_state.rs
  crates/loro-internal/src/state/map_state.rs
  crates/loro-internal/src/state/richtext_state.rs
  crates/loro-internal/src/state/tree_state.rs
Labels: refactor

#246 refactor: use rich text style config
  crates/examples/examples/draw.rs
  crates/loro-common/src/error.rs
  crates/loro-internal/src/configure.rs
  crates/loro-internal/src/container/richtext.rs
  crates/loro-internal/src/container/richtext/config.rs
  crates/loro-internal/src/container/richtext/richtext_state.rs
  crates/loro-internal/src/container/richtext/style_range_map.rs
  crates/loro-internal/src/delta/seq.rs
  crates/loro-internal/src/delta/text.rs
  crates/loro-internal/src/fuzz.rs
  crates/loro-internal/src/fuzz/richtext.rs
  crates/loro-internal/src/handler.rs
  crates/loro-internal/src/lib.rs
  crates/loro-internal/src/loro.rs
  crates/loro-internal/src/state.rs
  crates/loro-internal/src/state/richtext_state.rs
  crates/loro-internal/src/txn.rs
  crates/loro-internal/src/utils/lazy.rs
  crates/loro-internal/src/value.rs
  crates/loro-internal/tests/richtext.md
  crates/loro-internal/tests/richtext.rs
  crates/loro-internal/tests/test.rs
  crates/loro-wasm/src/lib.rs
  crates/loro/README.md
  crates/loro/src/lib.rs
  crates/loro/tests/loro_rust_test.rs
  loro-js/tests/richtext.test.ts
Labels: refactor

#257 feat: compare frontiers causal order
  crates/loro-internal/src/loro.rs
  crates/loro-internal/src/oplog.rs
  crates/loro-internal/src/oplog/dag.rs
  crates/loro-internal/src/version.rs
  crates/loro-wasm/src/lib.rs
  crates/loro/src/lib.rs
  crates/loro/tests/loro_rust_test.rs
  loro-js/tests/basic.test.ts
  loro-js/tests/checkout.test.ts
  loro-js/tests/version.test.ts
Labels: enhancement, linear
